version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.0
    - 12.6.2
  - dependency-name: lint-staged
    versions:
    - 10.2.13
    - 10.5.3
  - dependency-name: stylelint
    versions:
    - 13.7.2
    - 13.9.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.21.5
  - dependency-name: lodash
    versions:
    - 4.17.20
