[settings]
    ID = "091de6ff-ebf8-455b-8e5b-db2571213ac1"

# Build Settings
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
    command = "npm run build"
    functions = "functions"

# Build Plugins
# https://docs.netlify.com/configure-builds/build-plugins/

[[plugins]]
    package = "@netlify/plugin-functions-install-core"

# Redirects
# https://docs.netlify.com/routing/redirects/

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
